inputs:
  repo:
    description: 'Select another repository for finding actions cache'
    default: ${{ github.repository }}
  branch:
    description: 'Filter by branch'
    default: ''
  filter:
    description: 'Filter by key'
    default: ''
runs:
  using: composite
  steps:
    - run: |-
        ${{ github.action_path }}/clear-cache.sh 
        -R ${{ inputs.repo || '' }} 
        -B ${{ inputs.branch || '' }} 
        -F ${{ inputs.filter || '' }}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}