name: Build code base
Description: TODO

inputs:
  only-affected:
    default: false

runs:
  using: composite
  steps:
    - name: pre-compile
      shell: bash
      run: |
        pnpm build:cli
        pnpm install --offline --frozen-lockfile

    - name: Build project [all]
      if: ${{ inputs.only-affected == 'false' }}
      shell: bash
      run: pnpm build

    - name: Build project [affected]
      if: ${{ inputs.only-affected == 'true' }}
      shell: bash
      run: pnpm turbo run build --filter=...[origin/${{ github.base_ref }}]