name: Build documents

inputs:
  upload-artifact:
    default: true

runs:
  using: composite
  steps:
    - name: Setup node and install deps
      uses: ./.github/actions/node-setup

    - name: Generate version
      shell: bash
      run: pnpm changeset version
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Build storybook
      shell: bash
      run: pnpm build:docs

    - name: Upload artifact
      if: ${{ inputs.upload-artifact == 'true' }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./vue-press/dist
    