import type { ClientRequestInit, IHttpClient } from '@equinor/fusion-framework-module-http/client';

import { generateParameters } from './generate-parameters';

import type { ClientMethod } from '../../types';
import type { ApiResponse, ApiResult } from './types';

/**
 * Factory for creating a typed client function for the people resolve endpoint.
 *
 * The returned function will use the provided HTTP client and method to call the
 * resolve API for people identifiers, using parameters generated by
 * {@link generateParameters}.
 *
 * @param client - HTTP client used to execute the request
 * @param method - HTTP client method to invoke (for example, {@code 'json'})
 */
export const client =
  <
    TMethod extends keyof ClientMethod = keyof ClientMethod,
    TClient extends IHttpClient = IHttpClient,
  >(
    client: TClient,
    method: TMethod = 'json' as TMethod,
  ) =>
  <T = ApiResponse>(init?: ClientRequestInit<TClient, T>): ApiResult<TMethod, T> =>
    client[method](...generateParameters<T, TClient>(init)) as ApiResult<TMethod, T>;

export default client;
