name: Setup Node
Description: General setup of node
inputs:
  node-version:  
    default: 22
  turbo-cache:
    default: true

runs:
  using: composite
  steps:

    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    
    - name: Cache turbo build setup
      if: ${{ inputs.turbo-cache == 'true' }} 
      uses: rharkor/caching-for-turbo@v2.2.5

    - name: install
      shell: bash
      run: pnpm install
        