#!/usr/bin/env bash
set -euo pipefail

[[ "$ISSUE_NUMBER" =~ ^[1-9][0-9]{0,9}$ ]]
[[ "$BASE_SHA" =~ ^[a-f0-9]{40}$ ]]
[[ "$TASK_BRANCH" == "automation/issue-${ISSUE_NUMBER}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}" ]]
[[ "$GITHUB_REPOSITORY" == equinor/fusion-framework ]]
[[ -n "${GH_TOKEN:-}" ]]

test -f "$PATCH_PATH"
test -f "$PULL_REQUEST_PATH"
test -f "$EXECUTION_REPORT_PATH"
test -f "$CHECKSUM_PATH"
test "$(wc -c < "$PATCH_PATH")" -le 2097152
test "$(wc -c < "$PULL_REQUEST_PATH")" -le 32768
test "$(wc -c < "$EXECUTION_REPORT_PATH")" -le 2048
[[ "$(wc -l < "$CHECKSUM_PATH" | tr -d '[:space:]')" == 3 ]]
IFS= read -r patch_checksum < "$CHECKSUM_PATH"
IFS= read -r pull_request_checksum < <(sed -n '2p' "$CHECKSUM_PATH")
IFS= read -r execution_report_checksum < <(sed -n '3p' "$CHECKSUM_PATH")
patch_hash="$(sha256sum "$PATCH_PATH" | cut -d ' ' -f 1)"
pull_request_hash="$(sha256sum "$PULL_REQUEST_PATH" | cut -d ' ' -f 1)"
execution_report_hash="$(sha256sum "$EXECUTION_REPORT_PATH" | cut -d ' ' -f 1)"
[[ "$patch_checksum" == "$patch_hash  $(basename "$PATCH_PATH")" ]]
[[ "$pull_request_checksum" == "$pull_request_hash  $(basename "$PULL_REQUEST_PATH")" ]]
[[ "$execution_report_checksum" == "$execution_report_hash  $(basename "$EXECUTION_REPORT_PATH")" ]]

IFS= read -r title_line < "$PULL_REQUEST_PATH"
[[ "$title_line" =~ ^#\ (.+)$ ]]
pull_request_title="${BASH_REMATCH[1]}"
[[ "$pull_request_title" =~ ^(feat|fix|docs|refactor|test|chore)(\([a-z0-9-]+\))?:\ .+ ]]
[[ "${#pull_request_title}" -le 120 ]]
grep -Fq '**Why is this change needed?**' "$PULL_REQUEST_PATH"
grep -Fq '**What is the new behavior?**' "$PULL_REQUEST_PATH"
grep -Fq '**What is the intended behavior or invariant?**' "$PULL_REQUEST_PATH"
grep -Fq '**Does this PR introduce a breaking change?**' "$PULL_REQUEST_PATH"
grep -Fq '**Review guidance:**' "$PULL_REQUEST_PATH"
grep -Fq '### Checklist' "$PULL_REQUEST_PATH"
issue_relationships="$(
  grep -Ei \
    '^(close[sd]?|fix(e[sd])?|resolve[sd]?|refs?|related[[:space:]]+to):?[[:space:]]+#[0-9]+$' \
    "$PULL_REQUEST_PATH" ||
    true
)"
[[ "$issue_relationships" =~ ^(Resolves|Fixes)\ \#${ISSUE_NUMBER}$ ]] ||
  [[ "$issue_relationships" == "Related to #${ISSUE_NUMBER}" ]]
grep -Fq '## Work summary' "$EXECUTION_REPORT_PATH"
grep -Fq '## Validation' "$EXECUTION_REPORT_PATH"
if grep -Fq '<!--' "$PULL_REQUEST_PATH" || grep -Fq '<!--' "$EXECUTION_REPORT_PATH"; then
  echo 'Generated report contains an HTML comment opener.' >&2
  exit 1
fi

default_branch="$(gh api "repos/${GITHUB_REPOSITORY}" --jq .default_branch)"
[[ "$GITHUB_REF" == "refs/heads/${default_branch}" ]]
[[ "$(gh api "repos/${GITHUB_REPOSITORY}/commits/${default_branch}" --jq .sha)" == "$BASE_SHA" ]]
issue="$(gh api "repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}")"
[[ "$(jq --raw-output .state <<< "$issue")" == open ]]
[[ "$(jq --raw-output 'has("pull_request")' <<< "$issue")" == false ]]
[[ "$(git rev-parse HEAD)" == "$BASE_SHA" ]]
[[ -z "$(git status --porcelain)" ]]

git -c core.hooksPath=/dev/null apply --check --cached "$PATCH_PATH"
git -c core.hooksPath=/dev/null apply --cached "$PATCH_PATH"
paths=()
while IFS= read -r -d '' path; do
  paths+=("$path")
done < <(git diff --cached --name-only --no-renames -z)
(( ${#paths[@]} > 0 && ${#paths[@]} <= 100 ))

allowed_path='^(packages/|cookbooks/|vue-press/|eds/|contributing/|[.]changeset/|README[.]md$)'
for path in "${paths[@]}"; do
  check_path="${path#".changeset/"}"
  if ! [[ "$path" =~ $allowed_path ]] ||
    [[ "/$check_path/" == *"/."* ]] ||
    [[ "$path" == *\\* || "$path" == *$'\n'* || "$path" == *"/../"* ]] ||
    [[ "$path" == */AGENTS.md || "$path" == */CLAUDE.md || "$path" == */GEMINI.md ]]; then
    echo "Generated patch contains a disallowed path: $path" >&2
    exit 1
  fi
  entry="$(git ls-files --stage -- "$path")"
  if [[ -n "$entry" ]]; then
    mode="${entry%% *}"
    if [[ "$mode" != 100644 && "$mode" != 100755 ]]; then
      echo "Generated patch contains a disallowed file mode: $path ($mode)" >&2
      exit 1
    fi
  fi
done

body_file="$RUNNER_TEMP/pull-request-body.md"
{
  tail -n +3 "$PULL_REQUEST_PATH" | sed -e 's/@/\&commat;/g'
  printf '\n\n%s\n\n' '---'
  printf '%s\n\n' '> [!NOTE]'
  printf '%s\n\n' '> This draft was generated by the issue-solver workflow and requires human review.'
} > "$body_file"
test "$(wc -c < "$body_file")" -le 65536

if git ls-remote --exit-code --heads origin "refs/heads/${TASK_BRANCH}" >/dev/null 2>&1; then
  echo "Task branch already exists: $TASK_BRANCH" >&2
  exit 1
else
  status=$?
  [[ "$status" == 2 ]]
fi

git switch --create "$TASK_BRANCH"
git config user.name github-actions[bot]
git config user.email 41898282+github-actions[bot]@users.noreply.github.com
git -c core.hooksPath=/dev/null commit --message "$pull_request_title"
git push \
  --force-with-lease="refs/heads/${TASK_BRANCH}:" \
  origin \
  "HEAD:refs/heads/${TASK_BRANCH}"

pull_request_url="$(
  gh pr create \
    --repo "$GITHUB_REPOSITORY" \
    --draft \
    --base "$default_branch" \
    --head "$TASK_BRANCH" \
    --title "$pull_request_title" \
    --body-file "$body_file"
)"
gh pr ready "$pull_request_url" --repo "$GITHUB_REPOSITORY"
printf 'pull_request_url=%s\n' "$pull_request_url" >> "$GITHUB_OUTPUT"
