import { SearchClient, type SearchClientOptions } from '@azure/search-documents';
import type { KeyCredential, TokenCredential } from '@azure/core-auth';
import type {
  PipelinePolicy,
  PipelineRequest,
  PipelineResponse,
  SendRequest,
} from '@azure/core-rest-pipeline';
import type { AzureAISearchDocument } from '@langchain/community/vectorstores/azure_aisearch';

/**
 * Credential accepted by {@link FusionSearchClient}.
 *
 * - `TokenCredential` — standard MSAL / managed-identity flow (production).
 * - `KeyCredential` — used when bypassing the SDK's HTTPS-only bearer token
 *   check (local dev-server proxy).
 */
export type FusionSearchCredential = TokenCredential | KeyCredential;

/**
 * Azure Core pipeline policy that rewrites the OData action-suffixed paths
 * generated by `@azure/search-documents` to the simpler routes exposed by
 * the Fusion AI proxy.
 *
 * The standard Azure Search SDK generates action-qualified OData paths for
 * document operations which the Fusion proxy does not support. This policy
 * strips the action qualifier so requests are forwarded correctly.
 *
 * Path mappings:
 * - `/docs/search.index`       → `/docs/index`   (document upload/upsert/delete)
 * - `/docs/search.post.search` → `/docs/search`  (vector/hybrid search)
 *
 * @internal
 */
const fusionPathRewritePolicy: PipelinePolicy = {
  name: 'FusionAISearchPathRewrite',
  sendRequest(request: PipelineRequest, next: SendRequest): Promise<PipelineResponse> {
    // Rewrite OData action paths to Fusion proxy paths before the request is sent.
    request.url = request.url
      .replace(/\/docs\/search\.index\b/, '/docs/index')
      .replace(/\/docs\/search\.post\.search\b/, '/docs/search');
    return next(request);
  },
};

/**
 * Azure AI Search `SearchClient` pre-configured for the Fusion AI proxy.
 *
 * Injects {@link fusionPathRewritePolicy} so that the OData action paths
 * generated by `@azure/search-documents` are rewritten to match the simpler
 * route structure of the Fusion AI proxy.
 *
 * Passing this client directly to `AzureAISearchVectorStore` (via `config.client`)
 * also prevents LangChain from calling `ensureIndexExists` — the index is managed
 * externally by the Fusion AI service.
 *
 * @example
 * ```typescript
 * const client = new FusionSearchClient(
 *   'https://ai.test.api.fusion-dev.net',
 *   'my-index',
 *   tokenCredential,
 * );
 * const store = new AzureAISearchVectorStore(embeddings, { client });
 * ```
 */
export class FusionSearchClient extends SearchClient<AzureAISearchDocument> {
  /**
   * @param endpoint - Fusion AI service origin (e.g. `https://ai.test.api.fusion-dev.net`).
   * @param indexName - Name of the Azure AI Search index to target.
   * @param credential - Token credential or key credential used to authenticate requests.
   * @param options - Additional search client options forwarded to the Azure SDK.
   */
  constructor(
    endpoint: string,
    indexName: string,
    credential: FusionSearchCredential,
    options?: SearchClientOptions,
  ) {
    super(endpoint, indexName, credential, {
      ...options,
      additionalPolicies: [
        { policy: fusionPathRewritePolicy, position: 'perCall' },
        ...(options?.additionalPolicies ?? []),
      ],
    });
  }
}
