import { existsSync, globSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vuepress/core';

const includePattern = /<!--\s*@include:\s*([^\s#]+\.md)(?:#[^\s]+)?\s*-->/g;
const codeImportPattern = /@\[code[^\]]*\]\(([^)]+)\)/g;
const moduleBadgePattern = /<ModuleBadge\s+module="([^"]+)"[^>]*\/>/g;
const markdownLinkPattern = /\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g;
// Matches only raw <a href>, never `<RouteLink to>` — the latter is already a
// resolved, base-less route that vue-router prefixes with base at runtime.
const renderedLinkPattern = /(<a\s[^>]*\bhref=")([^"]+)(")/g;

export interface NamespaceRouteMaps {
  exact: Readonly<Record<string, string>>;
  aliases: Readonly<Record<string, string>>;
  sourceByRoute: Readonly<Record<string, string>>;
}

interface NamespaceRenderEnvironment {
  filePathRelative?: string;
}

/**
 * Resolves a VuePress source Markdown path to its public route.
 * @param sourcePath - Path relative to the VuePress source directory.
 * @returns The public route generated by VuePress.
 */
export const resolvePageRoute = (sourcePath: string): string => {
  const normalizedPath = sourcePath.split(path.sep).join('/');
  // README files publish as their containing directory.
  if (normalizedPath === 'README.md') {
    return '/';
  }
  // Nested README files publish as directory index routes.
  if (normalizedPath.endsWith('/README.md')) {
    return `/${normalizedPath.slice(0, -'README.md'.length)}`;
  }
  return `/${normalizedPath.replace(/\.md$/, '.html')}`;
};

/**
 * Discovers which repository Markdown files are published by VuePress wrapper pages.
 * @param sourceDir - Absolute VuePress source directory.
 * @param repoRoot - Absolute repository root directory.
 * @returns Exact repository namespace paths mapped to their public VuePress routes.
 */
export const createNamespaceRouteMap = (
  sourceDir: string,
  repoRoot: string,
): NamespaceRouteMaps => {
  const wrapperPaths = globSync('**/*.md', { cwd: sourceDir });
  const exact = Object.fromEntries(
    // Each wrapper owns the public route for every repository Markdown file it includes.
    wrapperPaths.flatMap((wrapperPath) => {
      const wrapperFile = path.resolve(sourceDir, wrapperPath);
      const content = readFileSync(wrapperFile, 'utf8');
      const includedRoutes = [...content.matchAll(includePattern)].flatMap((match) => {
        const includePath = match[1];
        const includedFile = path.resolve(path.dirname(wrapperFile), includePath);
        const namespacePath = path.relative(repoRoot, includedFile).split(path.sep).join('/');
        // Ignore includes outside the repository; all repository Markdown can own a public route.
        return !namespacePath.startsWith('../')
          ? [[namespacePath, resolvePageRoute(wrapperPath)] as const]
          : [];
      });
      const moduleRoutes = [...content.matchAll(moduleBadgePattern)].map(
        (match) => [`packages/${match[1]}/README.md`, resolvePageRoute(wrapperPath)] as const,
      );
      const sourceRoutes = [...content.matchAll(codeImportPattern)].map((match) => {
        const sourceFile = path.resolve(path.dirname(wrapperFile), match[1]);
        return [
          path.relative(repoRoot, sourceFile).split(path.sep).join('/'),
          resolvePageRoute(wrapperPath),
        ] as const;
      });
      return [...includedRoutes, ...moduleRoutes, ...sourceRoutes];
    }),
  );
  const aliases = Object.fromEntries(
    // Included relative links need aliases from their wrapper-relative route to the target wrapper.
    wrapperPaths.flatMap((wrapperPath) => {
      const wrapperFile = path.resolve(sourceDir, wrapperPath);
      const wrapperRoute = resolvePageRoute(wrapperPath);
      const content = readFileSync(wrapperFile, 'utf8');
      return [...content.matchAll(includePattern)].flatMap((includeMatch) => {
        const includedFile = path.resolve(path.dirname(wrapperFile), includeMatch[1]);
        // VuePress reports unresolved includes separately; they cannot provide route aliases.
        if (!existsSync(includedFile)) {
          return [];
        }
        const includedContent = readFileSync(includedFile, 'utf8');
        return [...includedContent.matchAll(markdownLinkPattern)].flatMap((linkMatch) => {
          const href = linkMatch[1];
          // Absolute, same-page, and protocol links do not participate in namespace routing.
          if (href.startsWith('/') || href.startsWith('#') || /^[a-z][a-z\d+.-]*:/i.test(href)) {
            return [];
          }
          const suffixIndex = href.search(/[?#]/);
          const linkPath = suffixIndex === -1 ? href : href.slice(0, suffixIndex);
          const targetPath = path.resolve(path.dirname(includedFile), linkPath);
          const targetSource = path
            .relative(repoRoot, targetPath)
            .split(path.sep)
            .join('/');
          const targetRoute =
            exact[targetSource] ??
            (existsSync(targetPath) && statSync(targetPath).isDirectory()
              ? wrapperRoute
              : undefined);
          // Missing files remain visible to link validation instead of falling back to a parent page.
          if (!targetRoute) {
            return [];
          }
          const publicLink = linkPath.replace(/\.md$/, '.html');
          const aliasRoute = new URL(publicLink, `https://docs.test${wrapperRoute}`).pathname;
          const sourceAlias = `/${targetSource}${linkPath.endsWith('/') ? '/' : ''}`;
          return [
            [aliasRoute, targetRoute] as const,
            [sourceAlias.replace(/\.md$/, '.html'), targetRoute] as const,
          ];
        });
      });
    }),
  );
  const sourceByRoute = Object.fromEntries(
    wrapperPaths.map((wrapperPath) => [resolvePageRoute(wrapperPath), wrapperPath]),
  );
  return { exact, aliases, sourceByRoute };
};

/**
 * Maps a repository namespace URL to the VuePress route publishing that source file.
 * @param href - Link target before or after VuePress base-path processing.
 * @param routeMap - Repository namespace paths mapped to public routes.
 * @param base - Configured VuePress deployment base.
 * @param currentRoute - Public route of the page containing a relative link.
 * @returns The mapped public URL, or the original URL when no wrapper publishes the target.
 */
export const rewriteNamespaceHref = (
  href: string,
  routeMaps: NamespaceRouteMaps,
  base: string,
  currentRoute?: string,
): string => {
  // External and protocol-relative URLs must never be interpreted as repository namespaces.
  if (/^(?:[a-z][a-z\d+.-]*:|\/\/)/i.test(href)) {
    return href;
  }
  const suffixIndex = href.search(/[?#]/);
  const pathname = suffixIndex === -1 ? href : href.slice(0, suffixIndex);
  const suffix = suffixIndex === -1 ? '' : href.slice(suffixIndex);
  const normalizedBase = base.endsWith('/') ? base.slice(0, -1) : base;
  const publicPath = pathname.startsWith(base) ? pathname.slice(normalizedBase.length) : pathname;
  const scopedPublicPath =
    currentRoute && !publicPath.startsWith('/')
      ? new URL(publicPath.replace(/\.md$/, '.html'), `https://docs.test${currentRoute}`).pathname
      : undefined;
  const aliasedRoute =
    (scopedPublicPath ? routeMaps.aliases[scopedPublicPath] : undefined) ??
    routeMaps.aliases[publicPath] ??
    routeMaps.aliases[publicPath.replace(/\.md$/, '.html')];
  // Resolve paths that the include plugin interpreted relative to the public wrapper.
  // Always base-prefix the result: on the pre-render pass this lets VuePress's own
  // resolver recognize the target as an internal route; on the post-render pass it
  // fixes hrefs VuePress left unresolved (still plain <a>, so base won't double up).
  if (aliasedRoute) {
    return `${normalizedBase}${aliasedRoute}${suffix}`;
  }
  const namespaceMatch = pathname.match(/(?:^|\/)(packages|cookbooks)\/(.+)$/);
  // Ordinary relative and external links are outside this plugin's namespace contract.
  if (!namespaceMatch) {
    return href;
  }
  const [, namespace, namespaceTarget] = namespaceMatch;
  const markdownTarget = namespaceTarget.endsWith('/')
    ? `${namespaceTarget}README.md`
    : namespaceTarget.replace(/\.html$/, '.md');
  const route = routeMaps.exact[`${namespace}/${markdownTarget}`];
  // Leave unmapped namespace links intact so link validation reports missing wrappers.
  if (!route) {
    return href;
  }
  return `${normalizedBase}${route}${suffix}`;
};

/**
 * Rewrites links from included `packages` and `cookbooks` Markdown into published VuePress routes.
 * @param repoRoot - Absolute repository root containing the namespace source directories.
 * @returns A VuePress plugin that derives mappings from existing `@include` wrappers.
 */
export const packageNamespaceLinksPlugin = (repoRoot: string): Plugin => (app) => {
  const routeMaps = createNamespaceRouteMap(app.options.source, repoRoot);
  return {
    name: 'package-namespace-links',
    extendsPage: (page) => {
      page.links = page.links.map((link) => {
        const mappedHref = rewriteNamespaceHref(link.raw, routeMaps, app.options.base, page.path);
        // Preserve links that do not target a published repository namespace.
        if (mappedHref === link.raw) {
          return link;
        }
        const normalizedBase = app.options.base.endsWith('/')
          ? app.options.base.slice(0, -1)
          : app.options.base;
        const mappedRoute = mappedHref.startsWith(app.options.base)
          ? mappedHref.slice(normalizedBase.length)
          : mappedHref;
        const routePath = mappedRoute.split(/[?#]/, 1)[0];
        const targetSource = routeMaps.sourceByRoute[routePath];
        // Leave unresolved routes visible to the built-in checker.
        if (!targetSource) {
          return link;
        }
        return { raw: targetSource, relative: targetSource, absolute: null };
      });
    },
    extendsMarkdown: (markdown) => {
      const originalLinkOpen =
        markdown.renderer.rules.link_open ??
        ((tokens, index, options, _env, renderer): string =>
          renderer.renderToken(tokens, index, options));

      markdown.renderer.rules.link_open = (tokens, index, options, env, renderer): string => {
        const token = tokens[index];
        const href = token.attrGet('href');
        const filePathRelative = (env as NamespaceRenderEnvironment).filePathRelative;
        const currentRoute = filePathRelative ? resolvePageRoute(filePathRelative) : undefined;
        // Rewrite the token when this plugin runs after the include path resolver.
        if (href) {
          token.attrSet(
            'href',
            rewriteNamespaceHref(href, routeMaps, app.options.base, currentRoute),
          );
        }
        const renderedLink = originalLinkOpen(tokens, index, options, env, renderer);
        // Only rewrite plain <a href> output. `<RouteLink to>` is already a resolved,
        // base-less internal route that vue-router prefixes with base at runtime;
        // rewriting it here would bake the base into the route and break navigation.
        return renderedLink.replace(
          renderedLinkPattern,
          (_match, prefix: string, value: string, suffix: string) =>
            `${prefix}${rewriteNamespaceHref(value, routeMaps, app.options.base, currentRoute)}${suffix}`,
        );
      };
    },
  };
};