import type { PayloadActionCreator } from './create-action';

/**
 * Returns the action type of an action creator generated by `createAction`.
 *
 * @template T - The action type string.
 * @param actionCreator - The action creator whose action type to get.
 * @returns The action type used by the action creator.
 */
export function getType<T extends string>(actionCreator: PayloadActionCreator<any, T>): T {
  return `${actionCreator}` as T;
}
