name: Setup Node
description: General setup of node
inputs:
  node-version:
    default: 24

runs:
  using: composite
  steps:

    - name: Disable turbo daemon for CI
      shell: bash
      run: echo "TURBO_DAEMON=false" >> "$GITHUB_ENV"

    - name: Setup pnpm
      uses: pnpm/action-setup@v5

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'


    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
