name: cache
permissions:
  contents: read
  actions: write    # Required for gh actions-cache delete command

on:
  workflow_dispatch:
    inputs:
      branch:
        description: name of the branch to filter, example refs/pull/1136/merge
        type: string
      filter:
        description: filter of keys to search for, example node-cache-Linux-
        type: string
      rebuild:
        description: when enabled, cache will be generated in the branch which action was called from
        type: boolean
        default: false
  workflow_call: 
    inputs:
      branch:
        description: name of the branch to filter, example refs/pull/1136/merge
        type: string
      filter:
        description: filter of keys to search for, example node-cache-Linux-
        type: string
      rebuild:
        description: when enabled, cache will be generated in the branch which action was called from
        type: boolean
        default: false

jobs:
  maintain:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v5

      - name: Setup node and install deps
        id: install
        if: ${{ inputs.rebuild == 'true' || inputs.rebuild == true }}
        uses: ./.github/actions/node-setup

      - name: Clear cache
        uses: ./.github/actions/clear-cache
        continue-on-error: true
        with:
          branch: ${{ inputs.branch }}
          filter: ${{ inputs.filter }}

      - name: Generate cache for source code
        if: ${{ steps.install.outcome == 'success' }}
        uses: ./.github/actions/build-packages
