name: cache

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
      filter:
        type: string
      rebuild:
        type: boolean
        default: false

  workflow_call: 
    inputs:
      branch:
        type: string
      filter:
        type: string
      rebuild:
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  maintain:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - name: Clear all cache on main branch
        uses: ./.github/workflows/actions/clear-cache
        continue-on-error: true
        with:
          branch: ${{ inputs.branch }}
          filter: ${{ inputs.filter }}

      - name: Setup node and install deps
        id: install
        if: ${{ inputs.rebuild == 'true' }}
        uses: ./.github/workflows/actions/node-setup

      - name: Generate cache for source code
        if: ${{ steps.install.outcome == 'success' }}
        uses: ./.github/workflows/actions/build-packages
