name: ci

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changsets:
    name: Version or publish packages
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Changeset
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'changesets.yml',
              ref: 'main',
            })



