name: ci

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changsets:
    name: Version or publish packages
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure git user (trigger actor) 
        uses: ./.github/workflows/actions/config-git-user
      
      - name: Setup node and install deps
        uses: ./.github/workflows/actions/node-setup

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: '🤖 Bip Bop - Fusion Framework Release'
          createGithubReleases: true
          setupGitUser: false
          version: pnpm changeset:version
          publish: pnpm changeset:publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: convert Changeset PR to draf
        if: steps.changesets.outputs.published == 'false'
        run: gh pr ready ${{ steps.changesets.outputs.pullRequestNumber }} --undo

      
          
  documentation:
    name: Merge main into docs
    runs-on: ubuntu-latest
    needs: changsets
    steps:
      - name: Update documentation
        uses: devmasx/merge-branch@1.4.0
        if: needs.changsets.outputs.published == 'true'
        with:
          type: now
          from_branch: main
          target_branch: docs
          github_token: ${{ github.token }}



