name: pr labels
on:
  workflow_call:

permissions: read-all

jobs:
  labeler:
    name: Auto-Label PRs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: fuxingloh/multi-labeler@v5.0.0