name: pr labels
on:
  pull_request_target:
    types: 
      - ready_for_review
      - opened 
      - synchronize

permissions: read-all

jobs:
  labeler:
    name: Auto-Label PRs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: fuxingloh/multi-labeler@v4.0.0