name: Release

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write

on:
  pull_request:
    types: [closed]

jobs:
  release-pkg:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node Dependencies
        run: yarn install --frozen-lockfile

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Bump versions
        run: |
          printf -v PR_BODY "%q" "${{ github.event.pull_request.body }}"
          PR_CHANGED_MODULES=$(npx lerna changed -l --loglevel "error")
          PR_MESSAGE="$PR_TITLE\n\n$PR_CHANGED_MODULES\n\n${PR_BODY}\n\n[pr-$PR_NUMBER]($PR_URL)"
          npx lerna version --yes --force-git-tag --conventional-graduate --create-release github -m "${PR_MESSAGE}"
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}

      - name: Release packages
        run: npx lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}