name: Release

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write

on:
  pull_request:
    types: [closed]

jobs:
  release-pkg:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node Dependencies
        run: yarn install --frozen-lockfile

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Bump versions
        run: |
        PR_MESSAGE="${{ github.event.pull_request.title }}\n\n$(npx lerna changed -l --loglevel \"error\")\n\n${{ github.event.pull_request.body }}\n\n[pr-${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})"
        npx lerna version --yes --force-git-tag --conventional-graduate --create-release -m "${PR_MESSAGE}" github 
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Release packages
        run: npx lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}