name: Test project files

on: 
  pull_request:
    paths:
      - '**.ts'
      - '**.tsx'

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Node Dependencies
        run: npm ci

      - run: npm test -- --runInBand --changedSince=main --testLocationInResults --json --coverage --outputFile="jest.results.json"

      - name: Test Code
        uses: mattallty/jest-github-action@v1.0.3
        with:
          changes-only: true
          test-command: "echo done"
        env:
          GITHUB_TOKEN: ${{ github.token }}
