name: Test project files

on: 
  pull_request:
    paths:
      - '**.ts'
      - '**.tsx'

jobs:
  jest:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: fetch changes since main
        run: 
          git fetch --no-tags --depth=1 origin main

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node Dependencies
        run: yarn install --frozen-lockfile

      - run: yarn test -- --runInBand --changedSince=origin/main --testLocationInResults --json --coverage --outputFile="jest.results.json"

      - name: Test Code
        uses: mattallty/jest-github-action@v1.0.3
        with:
          changes-only: true
          test-command: "echo done"
        env:
          GITHUB_TOKEN: ${{ github.token }}
