name: Run eslint and annotate
Description: TODO

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-latest
      node-version:
        type: number
        default: 18
   
runs:
  using: composite
  steps:
    - name: Run eslint
      shell: bash
      run: pnpm lint:report

    - name: Annotate Code Linting Results
      uses: ataylorme/eslint-annotate-action@1.1.2
      continue-on-error: true
      with:
        repo-token: "${{ github.token }}"
        report-json: "eslint-report.log.json"

    - name: Upload ESLint report
      uses: actions/upload-artifact@v4
      with:
        name: eslint-report.log.json
        path: eslint-report.log.json